---
title: "Evaluations of people, affection, and recommendation for a host country: A study of Global Korea Scholarship (GKS) recipients"
date: 2021-10
author:
  - name: Lisa Tam
    url: https://orcid.org/0000-0001-6520-6120
    orcid: 0000-0001-6520-6120
    affiliation: Queensland University of Technology
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
categories: [Scopus, Global Korea Scholarship, Korea, quantitative, people-to-people diplomacy, public diplomacy, 2021]
pub-info:
  reference: >-
    Lisa Tam and <strong>Kadir Jun Ayhan*</strong> (2021), “Evaluations of people, affection, and recommendation for a host country: A study of Global Korea Scholarship (GKS) recipients,” <em>Politics & Policy</em>: 49(6): 1292-1307, doi: <a href="https://doi.org/10.1111/polp.12438"><code>10.1111/polp.12438</code></a>
  extra: >-
    Supported by Korea Foundation 2018-2019 Policy-oriented Research Support Program.
doi: 10.1111/polp.12438
#image:
#draft: true
---

## Abstract

Extant research has examined the significance of interpersonal relationships in affecting public diplomacy outcomes. Relational public diplomacy is a long-term approach to public diplomacy which posits the importance of people-to-people exchange programs that facilitate two-way interactions between people from two different countries. Using survey data (*n* = 385) collected from alumni of the Global Korea Scholarship in 2018, this study found that respondents' perceptions of treatment by South Korean people influenced their comparisons of people from South Korea and their home countries. Moreover, the more highly they evaluated South Koreans compared to people in their home countries, the more likely it was that they would develop an affection and make positive recommendations toward South Korea as a destination for study and tourism. The empirical findings in this article have policy implications for scholarship programs as a public diplomacy tool beyond South Korea.

## Special Issue

This article is part of a special issue that uses our Global Korea Scholarship dataset. See other articles in the special issue [here](https://onlinelibrary.wiley.com/toc/17471346/2021/49/6).

## BibTeX citation

``` bibtex
@article{tam_evaluations_2021,
    title = {Evaluations of people, affection, and recommendation for a host country: A study of Global Korea Scholarship ({GKS}) recipients},
    volume = {49},
    issn = {1555-5623},
    doi = {10.1111/polp.12438},
    pages = {1292--1307},
    number = {6},
    journaltitle = {Politics \& Policy},
    author = {Tam, Lisa and Ayhan, Kadir Jun},
    date = {2021},
    note = {Type: Journal Article},
    keywords = {affection Asia Global Korea Scholarship P\&P Special Issue people-to-people exchanges public diplomacy South Korea Afecto Beca global de Corea Intercambios entre personas Diplomacia pública relacional Corea del Sur},
}
```
