---
title: "Branding Korea as “My Friend’s Country”: The Case of VANK"
date: 2018-02
author:
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
categories: [SSCI, public diplomacy, Korea, people-to-people diplomacy, non-state actors, country image, qualitative, mixed, 2018]
pub-info:
  reference: >-
    <strong>Kadir Jun Ayhan</strong> (2019), “Branding Korea as “My Friend’s Country”: The Case of VANK,” <em>Korea Observer</em>: 49(1): 51-81, doi: <a href="10.29152/KOIKS.2018.49.1.51"><code>10.29152/KOIKS.2018.49.1.51</code></a>
doi: 10.29152/KOIKS.2018.49.1.51
#image:
#draft: true
---

## **Abstract**

The role of non-state actors in public diplomacy remains an unsettled question in the literature. However, various transnational activities of non-state actors are often called public diplomacy, without discrimination. The lack of empirical studies on non-state public diplomacy is to blame for this conceptual confusion. Analytical and empirical studies of non-state public diplomacy are needed to consolidate this phenomenon, which is relatively new, while maintaining the conceptual clarity of public diplomacy. This study explores how Voluntary Agency Network of Korea (VANK), a Korean NGO, conducts public diplomacy and nation branding of Korea based on its members relationships with foreigners. To gain an in-depth understanding of VANK s activities from the perspectives of public diplomacy and nation branding, this study follows an exploratory single case study method. The findings of this article suggest how VANK and similar non-state actors offer potential for public diplomacy and nation branding that can be utilized also by state agencies.

## BibTeX citation

``` bibtex
@article{ayhan_branding_2018,
    title = {Branding Korea as “My Friend’s Country”: The Case of {VANK}'s Cyber Public Diplomats},
    volume = {49},
    doi = {10.29152/KOIKS.2018.49.1.51},
    pages = {51--81},
    number = {1},
    journaltitle = {Korea Observer},
    author = {Ayhan, Kadir Jun},
    date = {2018},
    note = {Type: Journal Article},
}
```
