---
title: "Capturing country images: a methodological approach"
date: 2021-03
author:
  - name: Efe Sevin
    url: https://linktr.ee/efesevin
    orcid: 0000-0002-7837-5000
    affiliation: Towson University
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
  - name: Diana Ingenhoff
    url: https://orcid.org/0000-0003-3034-3605
    orcid: 0000-0003-3034-3605
    affiliation: University of Fribourg
categories: [Scopus, Korea, quantitative, computational, public diplomacy, country image, 2021]
pub-info:
  reference: >-
    Efe Sevin*, Diana Ingenhoff, and <strong>Kadir Jun Ayhan</strong> (2021), “Capturing country images: a methodological approach,” <em>The Journal of International Communication</em>: 27(2): 237-257, doi: <a href="https://doi.org/10.1080/13216597.2021.1903965"><code>10.1080/13216597.2021.1903965</code></a>
  extra: >-
    Supported by Korean Studies Grant Program of the Academy of Korean Studies [grant number AKS-2019-R42].
doi: 10.1080/13216597.2021.1903965
#image:
#draft: true
---

## Abstract

Country images have been notoriously difficult to capture and measure effectively. In this article, we propose a methodological approach that combines designed and found data to capture public attitudes. We demonstrate how a mixed-method design with survey data and digital data -- namely tweets and Google Trends -- make it possible to better capture what target audiences think about a country. We make the case for such a combination by highlighting three aspects of country images. First, to understand what different types of public think about a country, we need to listen to different voices, and complement standardised public opinion survey data with open questions and digital data. Second, social media platforms are invaluable data resources as well as outlets that people on social media turn to for news and information. Last, digital data is unique and powerful, but difficult to analyse and interpret to create value for developing strategic communication policies. Public opinion survey data can help structure digital data and link both outcomes with each other. We support our methodological arguments through an illustrative study of the South Korean country image. We conclude our article by presenting a roadmap for multi-method analysis.

## BibTeX citation

``` bibtex
@article{sevin_capturing_2021,
    title = {Capturing country images: a methodological approach},
    volume = {27},
    issn = {1321-6597},
    doi = {10.1080/13216597.2021.1903965},
    pages = {237--257},
    number = {2},
    journaltitle = {The Journal of International Communication},
    author = {Sevin, Efe and Ayhan, Kadir Jun and Ingenhoff, Diana},
    date = {2021},
    note = {Type: Journal Article},
}
```
