---
title: "Rethinking Korean Middle Power Diplomacy as a Nation Branding Project"
date: 2019-02
author:
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
categories: [SSCI, international relations, reputation, Korea, foreign policy, diplomacy, development cooperation, qualitative, 2019]
pub-info:
  reference: >-
    <strong>Kadir Jun Ayhan</strong> (2019), “Rethinking Korean Middle Power Diplomacy as a Nation Branding Project,” <em>Korea Observer</em>: 50(1): 1-24, doi: <a href="10.29152/KOIKS.2019.50.1.1"><code>10.29152/KOIKS.2019.50.1.1</code></a>
doi: 10.29152/KOIKS.2019.50.1.1
#image:
#draft: true
---

## **Abstract**

South Korea's (hereafter Korea) recent middle power diplomacy has attracted worldwide attention. Korean administrations have attempted to steer the country along a middle power path, where it can play a more active global role that is commensurate with the size of its economy. Most accounts take Korea s self-declared identity as a middle power for granted; that is, they do not evaluate the non-conforming data. On the other hand, this paper traces the process of why the country projects a middle power identity. This paper first addresses alternative explanations of the positional, behavioral and identity approaches to answer this question. Following the failure of these explanations, this paper proposes that Korea s more assertive projection of its proclaimed middle power identity was a nation branding project that aimed to tackle the so-called Korea discount and to achieve its aspired place in the global prestige and status hierarchy. In turn, Korea envisioned its improved standing in the world helping it achieve its preferred global outcomes, particularly in shaping a favorable international environment surrounding the country.

## BibTeX citation

``` bibtex
@article{ayhan_rethinking_2019,
    title = {Rethinking Korea’s Middle Power Diplomacy as a Nation Branding Project},
    volume = {50},
    doi = {10.29152/KOIKS.2019.50.1.1},
    pages = {1--24},
    number = {1},
    journaltitle = {Korea Observer},
    author = {Ayhan, Kadir Jun},
    date = {2019},
    note = {Type: Journal Article},
}
```
