---
title: "R codes, packages, examples - Reminder for myself"
author: "Kadir Jun Ayhan"
date: last-modified
draft: true
categories: [useful links, R]
---

# Code (and project) examples for data analysis

## Project templates

-   by [Andrew Heiss](https://www.andrewheiss.com/research/)
-   by [Jordan Nafa](https://github.com/ajnafa/project-template) and [an example](https://github.com/ajnafa/linked-fate-paper)

## The use of world maps

-   by [Andrew Heiss](https://github.com/andrewheiss/taking-control-of-regulations/blob/master/analysis.Rmd)

-   by [Mike Flynn](https://github.com/meflynn/troops-book/blob/master/Code/Chapter-Contact/chapter-contact-code.Rmd)

## brms practices:

-   [brms vignettes hosted by Paul-Christian Bürkner](https://paul-buerkner.github.io/brms/articles/)

-   by [Mike Flynn](https://github.com/meflynn/troops-book/blob/master/Code/Chapter-Contact/chapter-contact-code.Rmd)

-   by [Jordan Nafa](https://github.com/ajnafa/linked-fate-paper)

-   by [Joshua Alley](https://github.com/Allisterh/Replication_econ-bargain-all/blob/aaba940d988579a1a933b732c3dc35c8ef6d8aea/data/us-exports.R)

-   by [Irena Chen](https://github.com/realirena/biostat_834_teaching_demo/blob/73dc3ceccae1124231fcfc097565456c470cda78/R/basic_lmm.R)

-   by [Daniel Viana](https://github.com/danielfvi/SustMPAs-Nutrition/blob/b8982e26647e2e43ec7d0d214a4ba236a5cc5c0e/Analysis/step1_Predicting_Biomass.R)

-   by [Kelvin Gorospe](https://github.com/jagephart/FishPrint/blob/8ce56f978944fb7a2010cd385a158f458aa1c987/bayes_02_impute_NA_vars.R)

-   by [Tobias Gerstenberg](https://psych252.github.io/psych252book/bayesian-data-analysis-2.html)

## Other

-   [The use of daggity for research and Andrew Heiss' other research](https://github.com/andrewheiss/taking-control-of-regulations/blob/master/analysis.Rmd) and [his other projects](https://www.andrewheiss.com/research/)

# Quarto

## Website - blog

Very good website, blog examples:

-   [Andrew Heiss](https://www.andrewheiss.com/)

-   [Mine Dogucu](https://www.minedogucu.com/)

-   [Mine Çetinkaya-Rundel](https://mine-cr.com/)

-   [Dr. Léo Belzile's class](https://edsm.rbind.io/)

Embedding social media posts: an extension: [quarto-social-embeds](https://github.com/sellorm/quarto-social-embeds)

Tutorials about using quarto for your blog or website:

-   [Building a Blog with Quarto](https://www.youtube.com/live/CVcvXfRyfE0?feature=share)

```{=html}
<!-- -->
```
-   [Switching to Quarto](https://jollydata.blog/posts/2022-08-06-switching-to-quarto/switching-to-quarto.html)

## Article authoring

Article Templates:

-   [Hikmah by Andrew Heiss](https://github.com/andrewheiss/hikmah-academic-quarto)
-   [rmd example by Andrew Heiss](https://github.com/andrewheiss/who-cares-about-crackdown/blob/master/manuscript/manuscript.Rmd), [another one](https://github.com/andrewheiss/cautioning-canary/blob/master/manuscript/manuscript.Rmd)
-   [by Jordan Nafa](https://github.com/ajnafa/linked-fate-paper)
-   [Latex pre-rint template](https://github.com/roaldarbol/LaPreprint/)
-   [Quarto journal templates](https://github.com/quarto-journals)

# Data Visualization

-   [R graph gallery, a collection of charts (and maps)](https://r-graph-gallery.com/index.html#google_vignette)

# Bayesian Data Analysis

## Books

[Statistical rethinking](https://xcelab.net/rm/statistical-rethinking/) and [lectures](https://youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus).

[Tidyverse translation of Statistical Rethinking](https://bookdown.org/content/4857/)

[Other brms translations for other Bayesian data analysis books](https://solomonkurz.netlify.app/book/) by [A. Solomon Kurz](https://solomonkurz.netlify.app/)

## Guides

-   [Prior Choice Recommendations (Gelman)](https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations)

-   [Bayestest: ROPE](https://easystats.github.io/bayestestR/articles/region_of_practical_equivalence.html)

-   [Bayestest: HDI](https://easystats.github.io/bayestestR/reference/hdi.html)

-   [Bayestest: Guidelines](https://easystats.github.io/bayestestR/articles/guidelines.html)

-   [A guide to correctly calculating posterior predictions and average marginal effects with multilievel Bayesian models - Andrew Heiss](https://www.andrewheiss.com/blog/2021/11/10/ame-bayes-re-guide/)

-   [A guide to working with country-year panel data and Bayesian multilevel models](https://www.andrewheiss.com/blog/2021/12/01/multilevel-models-panel-data-guide/)

-   [Extracting and visualizing tidy draws from brms models](https://cran.r-project.org/web/packages/tidybayes/vignettes/tidy-brms.html)

-   [Multi-level Modeling in RStan and brms (and the Mysteries of Log-Odds)](https://calogica.com/r/rstan/2020/07/05/season-pass-hierarchical-modelng-r-stan-brms.html)

## Packages

-   [Marginal effects](https://vincentarelbundock.github.io/marginaleffects/articles/brms.html)

-   [brmsmargins: A package that has functions to calculate marginal effects from brms models](https://joshuawiley.com/brmsmargins/)

-   [broom.mixed::augment()](https://cran.r-project.org/web/packages/broom.mixed/broom.mixed.pdf)

-   [broom.mixed::brms_tidiers](https://search.r-project.org/CRAN/refmans/broom.mixed/html/brms_tidiers.html)

-   [performance::r2_bayes or r2_posterior](https://easystats.github.io/performance/reference/r2_bayes.html)

-   [extract method for brmsfit objects](https://rdrr.io/cran/texreg/man/extract-brmsfit-method.html)

-   [LaTeX or HTML regression tables for MCMC Output](https://shanascogin.github.io/BayesPostEst/reference/mcmcReg.html)

# Other Data Analysis

-   [Diagnose data quality of variables: dlookr::diagnose](https://choonghyunryu.github.io/dlookr/articles/introduce.html)

-   [How to interpret linear models with the broom package in R](https://rforpoliticalscience.com/2022/10/24/how-to-interpret-linear-models-with-the-broom-package-in-r/)

-   [panelr: Wrangling and plotting panel data](https://rpubs.com/quarcs-lab/learn-panelr)
