project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-W257WPSHMV"
  title: "Dr. Kadir Jun Ayhan"
  page-footer:
    left: "© 2022 Kadir Jun Ayhan"
    center: "Prepared with [Quarto](https://quarto.org)"
  navbar:
    right:
      #- text: Blog
      #  href: blog.qmd 
      - icon: calendar-date
        href: https://calendly.com/kadirayhan/officehours
      - icon: envelope
        href: mailto:ayhan@ewha.ac.kr 
      - icon: github
        href: https://github.com/kjayhan
      - text: "{{< ai researchgate >}}"
        href: https://www.researchgate.net/profile/Kadir-Ayhan
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.co.kr/citations?user=TdrkBOUAAAAJ&hl=en
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0001-8052-1938
      - icon: twitter
        href: https://twitter.com/kadirayhan
      - icon: linkedin
        href: https://www.linkedin.com/in/kadirjunayhan/
    left:
      - href: index.qmd
        text: "About"
        file: index.qmd
      - text: "Research"
        file: research/index.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "CV"
        file: contents/cv/Kadir_Jun_Ayhan_CV.pdf
      - text: "Ongoing Research"
        file: ongoing.qmd
      #- text: "Special Lectures - 특강"
      #  file: lecture.qmd
      #- text: "Media"
      #  file: media.qmd
      - text: "Blog"
        file: blog.qmd
      #- text: "Useful Links"
      #  file: links.qmd
format:
  html:
    theme: flatly
    css: 
    - styles.css
    toc: true

editor: visual

