project:
  type: website
  output-dir: docs

website:
  title: "Dr. Kadir Jun Ayhan"
  page-footer:
    left: "© 2022 Kadir Jun Ayhan"
    center: "Prepared with [Quarto](https://quarto.org)"
  navbar:
    right:
      #- text: Blog
      #  href: blog.qmd 
      - icon: calendar-date
        href: https://calendly.com/kadirayhan/officehours
      - icon: envelope
        href: mailto:ayhan@ewha.ac.kr 
      - icon: github
        href: https://github.com/kjayhan
      - icon: twitter
        href: https://twitter.com/kadirayhan
      - icon: archive-fill
        href: https://www.researchgate.net/profile/Kadir-Ayhan
      - icon: google
        href: https://scholar.google.co.kr/citations?user=TdrkBOUAAAAJ&hl=en
      - icon: paperclip
        href: https://orcid.org/0000-0001-8052-1938
    
    left:
      - href: index.qmd
        text: "About"
        file: index.qmd
      - text: "Publications"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Ongoing Research"
        file: ongoing.qmd
      #- text: "Special Lectures - 특강"
      #  file: lecture.qmd
      #- text: "Media"
      #  file: media.qmd
      #- text: "Blog"
      #  file: blog.qmd
      #- text: "Links"
      #  file: links.qmd
format:
  html:
    theme: flatly
    css: 
    - styles.css
    #- academicons.css
    toc: true

editor: visual

