---
title: "Ongoing Research"
editor: visual
---

I am currently working on a few exciting projects. Here is a few of them without much details. If you are interested in any one of them, feel free to reach out to me.

-   The determinants of U.S. public diplomacy spending: I created a dataset (panel data) with U.S. public diplomacy spending and information on the host countries (trade with the US, trade dependence on Russia and China, terrorist attacks, US troops, UNGA voting similarity with the US etc.). I am currently writing a journal article based on my analysis of this data.

-   The determinants of U.S. overseas missions' budget: I am currently building a dataset (panel data) with U.S. overseas missions' budget as the main variable of interest and information on the host countries (trade with the US, trade dependence on Russia and China, terrorist attacks, US troops, UNGA voting similarity with the US etc.). This dataset is complementary to the aforementioned U.S. public diplomacy spending dataset.

-   The determinants of Korea's COVID-19 humanitarian aid. I created a dataset for this research project, and wrote a [working paper for KEI](https://keia.org/publication/south-koreas-public-diplomacy-during-the-covid-19-pandemic-seeking-status-as-an-authority-in-global-governance/) on a similar topic. Our abstract with Dr. Ryu Jeheung (Ewha Womans University) is accepted for ISA 2023 Annual Conference in Montreal. We presented the preliminary findings at Korean Association for Public Diplomacy and Korean Association for International Studies annual conferences in late 2022.

-   The determinants of Korean high-level diplomatic visits: I created a dataset (panel data) of Korean president and prime ministers' diplomatic visits abroad, and plan to run cross-sectional time-series logistic regression models of South Korean presidents' and prime ministers' diplomatic visits since the country's foundation in 1948. I am particularly interested in the differences between different time periods (pre-democracy, post-democracy) and how much this is linked to the country's status-seeking abroad (global vs. regional status hierarchy). I will present preliminary findings at ISA 2023 Annual Conference in Montreal as well as a workshop organized by *Pacific Affairs* in Toronto in March 2023. In the future, I plan to add Korean foreign ministers' diplomatic visits into the dataset as well. I plan to extend this research into Korea's all summit diplomacy by including high-level diplomatic visits into Korea by other countries' heads of government/ state.

-   [Public Diplomacy in Other Words](https://pdother.netlify.app/): This is a very exciting project I am organizing for [Journal of Public Diplomacy](https://www.journalofpd.com/). (We are still accepting interested scholars to join the project).

-   The determinants of Chinese outward FDI: I am co-authoring an article on the drivers of Chinese outward FDI with one my Ph.D. students (Yu Ren).

-   I have a few other paused or upcoming research projects.
