---
title: "Teaching"
editor: visual
---

I have taught the following courses in the past:

# Graduate School of International Studies, Ewha Womans University

Writing and Publishing a Journal
Article (Fall 2021, Fall 2022)

Soft Power in World Politics (Fall 2021)

International Security (Spring 2021, Spring 2022)

International Relations of East Asia (Spring 2021, Spring 2022)

**Ewha Womans University**
Introduction to International Politics (Division of International Studies) (Fall 2022)

Public Diplomacy (International Summer College 2022)

# Center for Teaching and Learning, Hankuk University of Foreign
Studies

Digital Active Learning Pedagogy (Fall 2020)

# Division of International Studies, Hankuk University of Foreign
Studies 

International Relations Theory (Spring / Fall 2018, Spring 2020)

Public Diplomacy (Spring 2017, Spring 2020)

Power in World Politics (Fall 2020)

International Relations of Asia (Fall 2020)

Transnational Actors in World Politics (Fall 2017 / 2018)

Global Governance and NGOs (Fall 2019, Fall 2020)

# Graduate School of International and Area Studies, Hankuk University of Foreign Studies 

Theory and Practice of Public Diplomacy (Fall 2017, Fall 2018, Fall, 2019)

Soft Power and International Development Cooperation (Fall 2017, Spring 2019)

Global Governance and NGOs (Spring 2017-2019)

Transnational Issues and Actors in World Politics (Spring 2017, Spring 2018, Fall 2019)

Policy Analysis Workshop (Fall 2018)

Professional Development Seminar (Fall 2018, Spring 2019)

# Graduate School of International Studies, Seoul National University

Theory and Practice of Public Diplomacy (Spring / Fall 2016)

Global Governance and NGOs (co-teaching, Fall 2015)

# Graduate School of International Studies, Ajou University 

Global Governance and NGOs (Fall 2016)

# Teaching-Related Certificates

2020, Participation Certificate, ISA-IPC Pandemic Pedagogy Workshop, Online (Zoom)

2018, Participation Certificate, International Studies Association Innovative Pedagogy Conference, St. Louis

2018,Participation Certificate, International Studies Association International Politics and Innovative Learning (IPIL) Network Working Group: Change in the Higher Education Landscape: The Power of Intercultural Networks in Innovative Learning
