---
title: "Satisfied or dissatisfied: The determinants of Global Korea Scholarship recipients’ satisfaction with life in Korea"
date: 2021-10
author:
  - name: Jae-Eun Jon
    url: https://sites.google.com/view/jaesson
    orcid: 0000-0001-9148-6410
    affiliation: Hankuk University of Foreign Studies
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
categories: [Scopus, Global Korea Scholarship, Korea, mixed, quantitative, people-to-people diplomacy, public diplomacy, 2021]
pub-info:
  reference: >-
    Jae-Eun Jon and <strong>Kadir Jun Ayhan*</strong> (2021), “Satisfied or dissatisfied: The determinants of Global Korea Scholarship recipients’ satisfaction with life in Korea,” <em>Politics & Policy</em>: 49(6): 1282-1291, doi: <a href="https://doi.org/10.1111/polp.12437"><code>10.1111/polp.12437</code></a>
  extra: >-
    Supported by Korea Foundation 2018-2019 Policy-oriented Research Support Program.
doi: 10.1111/polp.12437
#image:
#draft: true
---

## Abstract

Sponsored international student mobility programs are important public diplomacy tools for governments. These programs' positive outcomes are usually taken for granted and are rarely assessed. International students' satisfaction with life in the host country is an important variable for their behavioral outcomes related to the host country. This study used data from two surveys of Global Korea Scholarship (GKS) recipients from 136 countries to examine the determinants of their satisfaction with life in Korea. We found that students' cognitive and affective evaluations of Korea, frequency of Korean-language social interactions, and perceptions of their treatment by Koreans because of their nationality or religion were significant determinants of GKS students' satisfaction with life in Korea. In terms of demographic characteristics, men, students from developing countries, and those majoring in natural sciences or engineering fields were more satisfied than their peers. We discuss the implications of these findings for public diplomacy.

## Special Issue

This article is part of a special issue that uses our Global Korea Scholarship dataset. See other articles in the special issue [here](https://onlinelibrary.wiley.com/toc/17471346/2021/49/6).

## BibTeX citation

``` bibtex
@article{jon_satisfied_2021,
    title = {Satisfied or dissatisfied: The determinants of Global Korea Scholarship recipients’ satisfaction with life in Korea},
    volume = {49},
    issn = {1555-5623},
    doi = {10.1111/polp.12437},
    pages = {1391--1414},
    number = {6},
    journaltitle = {Politics \& Policy},
    author = {Jon, Jae-Eun and Ayhan, Kadir Jun},
    date = {2021},
    note = {Type: Journal Article},
    keywords = {Asia Global Korea Scholarship international student mobility P\&P Special Issue public diplomacy satisfaction South Korea Movilidad de estudiantes internacionales Diplomacia pública Beca global de Corea Satisfacción Corea del Sur Número especial de P\&P 國際學生流動 公共外交 全球韓國獎學金 滿意度 亞洲 韓國 P\&P 特刊},
}
```
