---
title: "About Ewha GSIS Computational Social Science Workshop"
author: "Kadir Jun Ayhan"
date: last-modified
categories: [Ewha GSIS, R]
draft: false
---

Dear [Ewha GSIS](http://gsis.ewha.ac.kr/) Students,

My first blog post is for you.

{{< tweet user=drob id=928447584712253440 >}}

Recently, I had to repeat myself while talking to a few students about Ewha GSIS Computational Social Science Workshop(s). Now, you and future students have this post instead!

# Why Computational Social Science?

Simply put, there is so much more data out there that is useful for social science research, and we have faster computers, and handy tools to analyze such data.

Ewha GSIS curriculum is quite rich in terms of theoretical and practical courses that equip you with theories and analytical frameworks to understand social issues. We also have courses that teach you quantitative and qualitative methodologies and research design. Yet, we don't have courses that teach computational methods/ tools that can handle big or complex data.

I want to provide you with this workshop opportunity basically to expose you to such methods/ tools so that you can continue learning them on your own.

In the age that we live in, I strongly believe that these computational methods/ tools will empower you in the job market given wide range of prospective jobs our graduates seek/ find (corporations, international organizations, think tanks, NGOs, media, academia etc.).

# Why R?

R is free! There are so many packages that are rich with a wide range of functions that you would need in all kinds of research, analysis, and reporting. Many more are being built as we speak. You can do from simple math to data pre-processing, from data visualization to regressions, from building your CV to building your website, from analyzing tweets to machine learning.

Python is probably getting more popular in the industry jobs in recent years. Yet, I think, for the time being, R is better suited for social science research. At least there are more books, tutorials, examples that you can learn from, I think.

Once exposed to R, you may also consider learning Python as well if it seems more attractive for you.

# "I don't know anything about coding! Indeed, I am frustrated about coding!"

Then this workshop is very much for you! I don't expect the students to have any prior knowledge of R, coding, or other statistical software. I organize this workshop mainly to expose students to R so that they can continue learning it. Learning curve is steep in the beginning. So you may need a trigger to begin and NOT GIVE UP. The workshop plays this role. So, long story short, no need to be intimidated by R (or your lack of background with coding).

But... continue to read the next section.

# How should I prepare for the workshop?

This is a one-day workshop on a Saturday. Don't expect to learn R in one-day! Equally, don't expect that we would be able to teach you R in one day. I designed the workshop mainly for practicing R, and troubleshooting with the help of the tutors. You will also learn from each other while collaborating in teams.

It means YOU MUST watch the [videos (Installing RStudio, R Basics, Data "Wrangling", Visualization, Modeling)](https://sicss.io/boot_camp/), install R and RStudio on your computers and follow the exercises in the videos BEFORE coming to the workshop.

Don't forget to bring your laptops (chargers etc.).

# What next?

Since 2022 Fall Semester, I organize two Ewha GSIS Computational Social Science Workshop(s) every semester. The first one is about the ABCs of R.

In the second workshop, I assume that you have at least some basic prior knowledge R (through the first workshop, self-study, taken a course etc.). The contents of the second workshop is still quite the basics of R, but if you don't have this prior knowledge, please watch the aforementioned videos and practice. That should get you going.

For those students who want to continue learning R, I can help facilitate a student-run (there must be volunteers for this) book club beginning with the [R for Data Science](https://r4ds.had.co.nz/) book.

If there is enough interest, we may consider offering a Data Science course in the future.

# Resources

[This is our workshop's repository.](https://github.com/kjayhan/Ewha_CSS_Workshop)

And here are more resources to help you study R.

R Book: [R for Data Science](https://r4ds.had.co.nz/)

Data Visualization Book: [Hands-on Data Visualization](https://handsondataviz.org/)

Book on Computational Social Science: [Bit by Bit](https://www.bitbybitbook.com/en/1st-ed/preface/)

Course: [Harvard on Edx - Data Science: R Basics](https://www.edx.org/course/data-science-r-basics)

Hands-on-practice: [Datacamp](https://www.datacamp.com)

For more free R books, see [Dr. Mine Dogucu's website](https://www.learnr4free.com/en/index.html)

Twitter: [Apply for Twitter's Academic API](https://developer.twitter.com/en/products/twitter-api/academic-research)

A Guide for a CSS Career: [A Three-Step Guide to Training Computational Social Science Ph.D. Students for Academic and Non-Academic Careers](https://osf.io/preprints/socarxiv/kgjn2/)

# Note

Please remember that this is an extracurricular activity that I organize on a Saturday. The preperations take a lot of my and Ms. Law's time. The only reason why I organize this is because I want to empower Ewha GSIS students with computational skills (or at least expose you to resources that would empower you). So take good advantage of the workshop.
