---
title: "Transferring Knowledge to Narrative Worlds: Applying Power Taxonomy to Science Fiction Films"
date: 2020-08
author:
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
categories: [SSCI, international relations, active learning pedagogy, power in world politics, 2020]
pub-info:
  reference: >-
    <strong>Kadir Jun Ayhan</strong> (2020), “Transferring Knowledge to Narrative Worlds: Applying Power Taxonomy to Science Fiction Films,” <em>International Studies Perspectives</em>: 21(3): 258-274, doi: <a href="https://doi.org/10.1093/isp/ekz024"><code>10.1093/isp/ekz024</code></a>
doi: 10.1093/isp/ekz024
#image:
#draft: true
---

## **Abstract**

Instructors of courses in international relations increasingly use films to facilitate students' learning of abstract concepts and to deepen their understanding of theories. This paper introduces how the fictional universes presented in films can be utilized as platforms for students to learn about the application of analytical frameworks. This method aims to enhance students' abilities to transfer learned knowledge to a different setting. Knowledge transfer requires skills that go beyond lower-order thinking. Higher-order thinking aids students' retention of concepts, and enables them to apply what they have learned to new situations. This article illustrates an application of a power taxonomy in the narrative world of the non-historical science fiction films. This exercise can easily be transported to various political science, international relations, and other courses to help students learn various analytical concepts, frameworks, and theories.

**Resumen:** Los instructores de cursos sobre relaciones internacionales utilizan cada vez más películas para facilitar el aprendizaje de conceptos abstractos por parte de los estudiantes y para profundizar su comprensión de las teorías. Este artículo explica cómo los universos ficticios de las películas se pueden utilizar como plataformas para que los estudiantes aprendan sobre la aplicación de marcos analíticos. Este método tiene como objetivo mejorar las habilidades de los estudiantes para transferir el conocimiento aprendido a un entorno diferente. La transferencia de conocimiento requiere de habilidades que van más allá del pensamiento de orden inferior. El pensamiento de orden superior ayuda a los estudiantes a retener los conceptos y les permite aplicar lo que han aprendido a nuevas situaciones. Este artículo ilustra la aplicación de una taxonomía de poder en el mundo narrativo de las películas de ciencia ficción que no se relacionan con un evento histórico. Este ejercicio se puede aplicar fácilmente a diversos cursos de ciencias políticas, relaciones internacionales y otra índole para ayudar a los estudiantes a aprender diferentes conceptos analíticos, marcos y teorías.

**Résumé:** Les enseignants en relations internationales ont de plus en plus recours aux films pour faciliter l'assimilation par les étudiants de concepts abstraits et pour approfondir leur compréhension des théories. Cet article montre comment les univers fictifs présentés dans les films peuvent être utilisés comme des plateformes pour que les étudiants comprennent l'application des contextes analytiques. Cette méthode vise à renforcer les capacités des étudiants à transférer les connaissances acquises dans un contexte différent. Le transfert de connaissances requiert des compétences qui dépassent la pensée d'ordre inférieur. La pensée d'ordre supérieur aide les étudiants à retenir les concepts et leur permet d'appliquer ce qu'ils ont appris à des nouvelles situations. Cet article illustre une application d'une taxonomie de pouvoir dans le monde narratif des films de science-fiction non-historiques. Cet exercice peut facilement être transposé à différents cours de sciences politiques, relations internationales etc. afin d'aider les étudiants à apprendre différents concepts, cadres et théories analytiques.

## BibTeX citation

``` bibtex
@article{ayhan_transferring_2020,
    title = {Transferring Knowledge to Narrative Worlds: Applying Power Taxonomy to Science Fiction Films},
    volume = {21},
    doi = {10.1093/isp/ekz024},
    pages = {258--274},
    number = {3},
    journaltitle = {International Studies Perspectives},
    author = {Ayhan, Kadir Jun},
    date = {2020},
    note = {Type: Journal Article},
    keywords = {film},
}
```
