---
title: "About me"
---

I am an Assistant Professor of International Relations at Ewha Womans University Graduate School of International Studies. My main research interests include public diplomacy, power in world politics, Korean foreign policy, status and reputation, and international student mobility. I serve as the Editor-in-chief of Journal of Public Diplomacy. I regularly consult for governmental public diplomacy projects in Korea, including as a member of Korea Foundation Steering Advisory Committee for Empowerment of Cultural Exchanges and Cooperation. I served as a member of the Korean Presidential National Unity Committee in 2022. I received my Ph.D. (2016) and M.I.S. (2010) from Seoul National University in International Studies and Bachelor of Commerce (2008) in Economics and International Trade from the University of Auckland. I published peer-reviewed articles in numerous journals such as International Studies Perspectives, Korea Observer, Asia Pacific Education Review, Politics & Policy, Place Branding and Public Diplomacy, and Asian International Studies Review among others.

# **Contact**

You can contact me via [email](mailto:ayhan@ewha.ac.kr) or via [Twitter DM](https://twitter.comkadirayhan).
