---
title: "Non-Coercive Influence in World Politics: Intersection with State Inclusive Index"
date: 2021-03
author:
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
  - name: Efe Sevin
    url: https://linktr.ee/efesevin
    orcid: 0000-0002-7837-5000
    affiliation: Towson University
categories: [public diplomacy, evaluation, 2021]
pub-info:
  reference: >-
    <strong>Kadir Jun Ayhan*</strong> and Efe Sevin (2021), “Non-Coercive Influence in World Politics: Intersection with State Inclusive Index,” in J. Park & H.-S. Lyu (eds.) <em>Developing State Inclusiveness Index: Conceptualization and Measurement</em> (pp. 419-435), National Research Council for Economics, Humanities and Social Sciences. <a href="https://www.kipa.re.kr/site/mblk/research/selectBaseView.do?gubun=CO&seqNo=BASE_000000000000634"><code>link</code></a>
#image:
#draft: true
---

## Introduction

In this chapter, we were tasked with finding correlations between State Inclusiveness Index (SII) and soft power in world politics. As we suspected, this was not an easy task since measuring power, particularly soft power, is not straightforward. In Joseph Nye's words "\[p\]ower is also like love, easier to experience than to define or measure, but no less real for that" (Nye, 2004: 1). Indices that measure a country's soft power, or other indices that rank countries' influence in other dimensions of world politics, have their share of conceptual and methodological problems. Most measurements fail to control for coercion and inducement and end up finding high correlations between hard and soft power (Singh & MacDonald, 2017). Despite the problems with soft power as a concept (Ayhan, 2020; Bially Mattern, 2005), and shortcomings of its measurement attempts (Singh & MacDonald, 2017; Yun, 2018), they are not without their merits since they present a relative -- albeit incomplete -- picture of a country's assets. Using these measures, we aim to examine how a country's multidimensional inclusiveness may be correlated with its relative influence in world politics by looking at various datasets that give us proxies for non-coercive influence in world politics.

...

## Korean Translation

The book was translated into Korean as well. You can find the BibTex citation for both books below.

## BibTeX citation (English version)

``` bibtex
@incollection{ayhan_non-coercive_2021,
    location = {Seoul},
    title = {Non-Coercive Influence in World Politics: Intersection with State Inclusive Index},
    url = {https://www.kipa.re.kr/site/mblk/research/selectBaseView.do?gubun=CO&seqNo=BASE_000000000000634},
    pages = {419--435},
    booktitle = {Developing State Inclusiveness Index: Conceptualization and Measurement},
    publisher = {National Research Council for Economics, Humanities and Social Sciences},
    author = {Ayhan, Kadir Jun and Sevin, Efe},
    editor = {Park, June and Lyu, Hyeon-Seok},
    date = {2021},
    note = {Type: Book Section},
}
```

## BibTeX citation (Korean version)

``` bibtex
@incollection{ayhan__2021,
    location = {서울},
    title = {세계정치에서의 비강압적 영향력: 국가포용성지수와의 교차점},
    url = {https://www.nrc.re.kr/board.es?mid=a10301000000&bid=0008&act=view&otp_id=OTP_0000000000006923},
    pages = {419--435},
    booktitle = {국가포용성지수 개발 연구},
    publisher = {한국행정연구원},
    author = {Ayhan, Kadir Jun and Sevin, Efe},
    editor = {박준},
    date = {2021},
}
```
