---
title: "Useful links"
author: "Kadir Jun Ayhan"
date: last-modified
categories: [useful links]
draft: false
---

# Self-studying statistics

## Statistical Rethinking

A great [book](https://xcelab.net/rm/statistical-rethinking/) and even greater [lectures](https://www.youtube.com/playlist?list=PLDcUM9US4XdMROZ57-OIRtIK0aOynbgZN) by a top scholar, [Richard McElreath](https://xcelab.net/rm/). (He is recently uploading the 2023 version of the lectures [here](https://youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus).

There is a tidyverse translation of the book [here](https://bookdown.org/content/4857/) by [A. Solomon Kurz](https://solomonkurz.netlify.app/).

All the better, "rethinking" involves Bayesian approach to inference, rather than a frequentist one.

## Regression and Other Stories

A great book by three legends of Bayesian Data Analysis: [Regression and Other Stories](https://avehtari.github.io/ROS-Examples/) by [Andrew Gelman](http://www.stat.columbia.edu/~gelman/), [Jennifer Hill](https://steinhardt.nyu.edu/people/jennifer-hill), and [Aki Vehtari](https://users.aalto.fi/~ave/). You can find [free online pdf of the book](https://users.aalto.fi/~ave/ROS.pdf), [the code and data for the examples](https://avehtari.github.io/ROS-Examples/examples.html) and more from the links.

Once you are done with this book, the next stage could be [Bayesian Data Analysis](http://www.stat.columbia.edu/~gelman/book/) by Andrew Gelman, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin. This book's [pdf is also freely available on their website](http://www.stat.columbia.edu/~gelman/book/BDA3.pdf).

Aki Vehtari also provide [freely available course](https://avehtari.github.io/BDA_course_Aalto/) using this book. However, both BDA and Aki's lectures are more advanced than Statistical Rethinking, and Regression and Other Stories.

## The Effect: An Introduction to Research Design and Causality

This [book](https://theeffectbook.net/) by [Nick Huntington-Klein](https://www.nickchk.com/) is more student-friendly I should say. It is a great introduction to econometrics with [code examples in R, Stata and Python](https://theeffectbook.net/)

You can find the course lectures [here](https://youtube.com/playlist?list=PLcTBLulJV_AK1hKtnO0-kYrU0D09K-kj8).

# Resources for R

[R for Data Science](https://r4ds.had.co.nz/) by [Hadley Wickham](https://hadley.nz), [Mine Çetinkaya-Rundel](https://mine-cr.com/), and [Garrett Grolemund](https://www.rstudio.com/authors/garrett-grolemund/).

[Hands-on Data Visualization](https://handsondataviz.org/)

Course: [Harvard on Edx - Data Science: R Basics](https://www.edx.org/course/data-science-r-basics)

[8-week R course with great best-practices tips](https://www.stephaniehicks.com/jhustatcomputing2022/schedule) by [Stephanie Hicks](https://www.stephaniehicks.com/)

Hands-on-practice: [Datacamp](https://www.datacamp.com)

For more free R books, see [Dr. Mine Dogucu's website](https://www.learnr4free.com/en/index.html)
