---
title: "Determinants of Global Korea Scholarship: Students’ word-of-mouth about Korea"
date: 2021-08
author:
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
  - name: Moamen Gouda
    url: https://sites.google.com/site/moamengoudaecon
    orcid: 0000-0002-6685-7264
    affiliation: Hankuk University of Foreign Studies
categories: [SSCI, Global Korea Scholarship, Korea, quantitative, people-to-people diplomacy, public diplomacy, country image, 2021]
pub-info:
  reference: >-
    <strong>Kadir Jun Ayhan*</strong> and Moamen Gouda (2021), “Determinants of Global Korea Scholarship: Students’ word-of-mouth about Korea,” <em>Asia Pacific Education Review</em>: 22(1): 15-29, doi: <a href="https://doi.org/10.1007/s12564-020-09648-8"><code>10.1007/s12564-020-09648-8</code></a>
  extra: >-
    Supported by Korea Foundation 2018-2019 Policy-oriented Research Support Program.
doi: 10.1007/s12564-020-09648-8
#image:
#draft: true
---

## Abstract

International student-mobility programs are one of the core programs countries employ as part of their public diplomacy portfolio. Policymakers assume that sponsored foreign students would develop positive beliefs about and emotions towards the host country, which in turn would lead to favorable behavior towards it. However, evaluations of such programs from a public diplomacy perspective are rare and Western-centric. In this paper, we analyze how Global Korea Scholarship students' cognitive and affective evaluations of Korea influence their country image and word-of-mouth about Korea; i.e., in how they voluntarily share their experiences in Korea with others. We use variance-based partial least squares structural equation modeling (PLS-SEM) to analyze the data obtained from surveying 1107 scholarship holding foreign students. Our findings suggest that students evaluate Korea most positively in terms of its culture and nature, while their evaluations are not as positive in terms of the integrity and values of the country. For positive word-of-mouth, affection towards Korea plays the most significant role, while for negative word-of-mouth, the students' beliefs about the country's integrity and values had the most influence. Our findings help identify the strengths and weaknesses in Korea's country image which can, in turn, inform and shape policies accordingly.

## Correction

A correction was published for this article:

Ayhan, K.J., Gouda, M. Correction to: Determinants of Global Korea Scholarship students' word‑of‑mouth about Korea. Asia Pacific Educ. Rev. 22, 579--582 (2021). [doi: 10.1007/s12564-020-09648-8](https://doi.org/10.1007/s12564-021-09712-x)

## BibTeX citation

``` bibtex
@article{ayhan_determinants_2021,
    title = {Determinants of Global Korea Scholarship students’ word-of-mouth about Korea},
    volume = {22},
    issn = {1876-407X},
    doi = {10.1007/s12564-020-09648-8},
    pages = {15--29},
    number = {1},
    journaltitle = {Asia Pacific Education Review},
    author = {Ayhan, Kadir Jun and Gouda, Moamen},
    date = {2021},
    note = {Type: Journal Article},
}
```
