---
title: "Impact of Country Image on Relationship Maintenance: A Case Study of Korean Government Scholarship Program Alumni"
date: 2022-04
author:
  - name: Eriks Varpahovskis
    url: https://www.scopus.com/authid/detail.uri?authorId=57218514504
    orcid: 0000-0002-6740-6377
    affiliation: National Research University Higher School of Economics
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
categories: [Scopus, Global Korea Scholarship, mixed, people-to-people diplomacy, public diplomacy, country image, 2022]
pub-info:
  reference: >-
    Eriks Varpahovskis and <strong>Kadir Jun Ayhan*</strong> (2022), “Impact of Country Image on Relationship Maintenance: A Case Study of Korean Government Scholarship Program Alumni,” <em>Place Branding and Public Diplomacy</em>: 18(3): 201-203, doi: <a href="https://doi.org/10.1057/s41254-020-00177-0"><code>10.1057/s41254-020-00177-0</code></a>
  extra: >-
    Supported by Korea Foundation 2018-2019 Policy-oriented Research Support Program.
doi: 10.1057/s41254-020-00177-0
#image:
#draft: true
---

## Abstract

Governments sponsor student-mobility programs with the expectation that students will build a more favorable and informed opinion of the host country which, in turn, will determine more favorable behavior towards the host country. Nevertheless, assessments of this logic are rare. Based on a survey of the Korean Government Scholarship Program's alumni (*n* = 579), we analyze the alumni's country image of South Korea and how this image determines their relationship maintenance behavior with South Korean people. Our findings show that the KGSP alumni's image of South Korea partly explains the variance in their personal and professional relationship maintenance with South Koreans. Our findings show that the alumni's emotions about South Korea influence their personal relationship maintenance behavior more than does each of the cognitive dimensions of the country image, while the functional dimension, which evaluates their beliefs about the country's competencies and the competitiveness of its economic and political systems, has the highest influence on the alumni's professional relationship maintenance.

## BibTeX citation

``` bibtex
@article{varpahovskis_impact_2022,
    title = {Impact of country image on relationship maintenance: a case study of Korean Government Scholarship Program alumni},
    volume = {18},
    issn = {1751-8059},
    doi = {10.1057/s41254-020-00177-0},
    pages = {52--64},
    number = {2},
    journaltitle = {Place Branding and Public Diplomacy},
    author = {Varpahovskis, Eriks and Ayhan, Kadir Jun},
    date = {2022},
    note = {Type: Journal Article},
}
```
