---
title: "International scholarship for social change? Re-contextualizing Global Korea Scholarship alumni’s perceptions of justice and diversity in South Korea"
date: 2021-10
author:
  - name: Moon Suk Hong
    url: https://www.google.com/search?q=moon+suk+hung&oq=moon+suk+hung&aqs=chrome..69i57.2427j0j4&sourceid=chrome&ie=UTF-8#:~:text=Moon%20Suk%20Hong%20%2D%20Busan,academia.edu%20%E2%80%BA%20MoonSukHong
    orcid: 0000-0002-8208-8573
    affiliation: Busan University of Foreign Studies
  - name: Minjeong Jeon
    url: https://snu-kr.academia.edu/MinjeongJeon
    orcid: 0000
    affiliation: Seoul National University
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
categories: [Scopus, Global Korea Scholarship, Korea, mixed, people-to-people diplomacy, public diplomacy, 2021]
pub-info:
  reference: >-
    Moon Suk Hong, Minjeong Jeon*, and <strong>Kadir Jun Ayhan</strong> (2021), “International scholarship for social change? Re-contextualizing Global Korea Scholarship alumni’s perceptions of justice and diversity in South Korea,” <em>Politics & Policy</em>: 49(6): 1359-1390, doi: <a href="https://doi.org/10.1111/polp.12435"><code>10.1111/polp.12435</code></a>
  extra: >-
    Supported by Korea Foundation 2018-2019 Policy-oriented Research Support Program.
doi: 10.1111/polp.12435
#image:
#draft: true
---

## Abstract

This study examines South Korea's international scholarship program based on responses to the Global Korea Scholarship (GKS) alumni survey to find how the participants perceive the host country's dimensions of justice and diversity. We employ the concept of justice in terms of redistribution, recognition, and representation. Analysis of GKS alumni perceptions of Korean society revealed that international mobility programs may provide positive and negative experiences for the participants depending on their positionality in terms of gender, ethnicity, and Korean language proficiency. Some had the exclusive opportunity to access global knowledge, skills, and networks. Others were exposed to unexpected misrepresentation and misframing while living and learning in the new society. We suggest the need for multidimensional policy discussions to consider both positive and negative outcomes of international scholarship programs and their potential to play a transformative role in global higher education.

## Special Issue

This article is part of a special issue that uses our Global Korea Scholarship dataset. See other articles in the special issue [here](https://onlinelibrary.wiley.com/toc/17471346/2021/49/6).

## BibTeX citation

``` bibtex
@article{hong_international_2021,
    title = {International Scholarship for Social Change? Re-contextualizing Global Scholarship Alumni’s Perceptions of Diversity and Justice in South Korea},
    volume = {49},
    doi = {10.1111/polp.12435},
    number = {6},
    journaltitle = {Politics \& Policy},
    author = {Hong, Moon Suk and Jeong, Minjeong and Ayhan, Kadir Jun},
    date = {2021},
    note = {Type: Journal Article},
}
```
