---
title: "Inter-Korean People-to-People Diplomacy: Social and Cultural Exchanges across the 38th Parallel"
date: 2023-01
author:
  - name: Kadir Jun Ayhan
    url: https://kjayhan.github.io
    orcid: 0000-0001-8052-1938
    affiliation: Ewha Womans University Graduate School of International Studies
  - name: Siyeon Jang
    url: https://hufs.academia.edu/%EC%8B%9C%EC%97%B0%EC%9E%A5
    orcid: 0000-0002-4105-4449
    affiliation: Hankuk University of Foreign Studies
categories: [Scopus, Korea, Inter-Korean, qualitative, people-to-people diplomacy, public diplomacy, evaluation, foreign policy, international relations, 2023]
pub-info:
  reference: >-
    <strong>Kadir Jun Ayhan</strong> and Siyeon Jang* (2023), “Inter-Korean People-to-People Diplomacy: Social and Cultural Exchanges across the 38th Parallel,” <em>The Hague Journal of Diplomacy</em>: 18(1): 95-132, doi: <a href="https://doi.org/10.1163/1871191x-bja10139"><code>10.1163/1871191x-bja10139</code></a>
  extra: >-
    Supported by Korea Foundation 2018-2019 Policy-oriented Research Support Program.
doi: 10.1163/1871191x-bja10139
#image:
#draft: true
---

## Abstract

The people of the two Koreas cannot communicate directly with one another. Since the early 1990s, South and North Korea have allowed a limited number of people-to-people exchanges. In this article, we map the South Korean government's theories of change regarding inter-Korean exchanges based on policy documents and semi-structured interviews with five high-level Ministry of Unification bureaucrats. We also explore the outcomes of inter-Korean exchanges, building on ten South Korean participants' insights. Our findings suggest that the primary goals of inter-Korean social and cultural exchanges have been to expand contact between the two Koreas to alleviate the sense of mutual alienation, to increase empathy and, in turn, to reduce tensions and establish peace on the Korean Peninsula. Participant interviews reveal that direct interpersonal interaction between South and North Koreans reinforces the idea of a superordinate Korean group identity.

## BibTeX citation

``` bibtex
@article{ayhan_inter-korean_2023,
    title = {Inter-Korean People-to-People Diplomacy: Social and Cultural Exchanges across the 38th Parallel},
    volume = {18},
    url = {https://brill.com/view/journals/hjd/aop/article-10.1163-1871191x-bja10139/article-10.1163-1871191x-bja10139.xml},
    doi = {10.1163/1871191x-bja10139},
    pages = {95--132},
    number = {1},
    journaltitle = {The Hague Journal of Diplomacy},
    author = {Ayhan, Kadir Jun and Jang, Siyeon},
    date = {2023},
    note = {Place: Leiden, The Netherlands
Publisher: Brill {\textbar} Nijhoff},
}
```
