---
title: "Mid-term Instructions"
subtitle: "Ewha GSIS Spring 2023: International Security"
author: Dr. Kadir Jun Ayhan
---

**Due date:** 20 Apr 23:59

**Submission:** CyberCampus

**Word count:** 900-1100 words

**Guiding Questions**[^1]

[^1]: Much of this content is adapted from the supplementary file provided by [Eric R Rittinger](https://www.salisbury.edu/faculty-and-staff/errittinger). I appreciate him for making these materials available for adaptation.

1.	What lessons, if any, about international security did you take away from playing Diplomacy?

2.	Did any country, including yours, build a reputation that mattered in the game? How did it matter if it did?

3.	How does Diplomacy simplify real-life international security? What does the game leave out? How can you explain what the game leaves out with different international security theories/ approaches/ frameworks?


As you write your answer, make sure to:

•	Consider what we covered so far in class.

•	Use your words economically. That is, do not have unnecessary words to fill the word count. Stay on point.

•	Explain your arguments clearly and make connection with course contents (lecture notes, course readings, class discussion etc.) to support your arguments.

•	Proofread using your word processor.

•	In addition to your own ideas, refer ONLY to the assigned required/ recommended articles. Use proper citation and referencing (any style is fine as long as it is consistent). Plagiarism will not be tolerated. 

•	Make sure NOT to search your answer on the internet. As stated above, limit your research to course contents (assigned readings, lecture notes etc.). Make sense of what happened in the game, by applying what you learned during the course. Do this on your own.

I will evaluate you based on the following criteria:

•	Does the essay make clear and logical connections to different international security theories/ perspectives/ concepts that we covered in this class?

•	Is the essay proofread? (I am not looking for perfect English as most of you are not native speakers. But pay attention to what you write, and make sure to use spelling and grammar check function of your word processor)

•	Does the essay have clear arguments and is it well-organized?
